<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__btnWrite</name>
   <tag></tag>
   <elementGuidId>b7c6ff1c-215c-444c-a5c1-a263fe594b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btnWrite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;메일쓰기&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35bbb62a-d5e2-4c87-9406-09a1520afed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>main.php?page=write</value>
      <webElementGuid>34cb6aa0-d213-45dc-a54d-3cd6045fa2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnWrite</value>
      <webElementGuid>82c10f8b-8846-4a39-858c-01a5aca2d179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>메일쓰기</value>
      <webElementGuid>6354fe6f-febd-4f71-bb79-350a4502c535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;snb&quot;]/div[@class=&quot;button&quot;]/a[@class=&quot;btnWrite&quot;]</value>
      <webElementGuid>dc3e02e9-0a69-4a7f-ba20-eb90a658d313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/div/div/a</value>
      <webElementGuid>117f08b8-88d6-4a1d-976e-f21b229c40de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'메일쓰기')]</value>
      <webElementGuid>af8523e4-a78e-4cf1-b1bf-f5fff735266d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='메일함 메뉴'])[1]/following::a[1]</value>
      <webElementGuid>a5d791e1-6011-415b-a5ac-df98c0f89453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPF 설정'])[1]/following::a[1]</value>
      <webElementGuid>c347756d-a42f-40f0-ad34-74739c0aacd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내게쓰기'])[1]/preceding::a[1]</value>
      <webElementGuid>5f5981af-a70a-42c2-870f-97a67858651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='안읽음'])[1]/preceding::a[2]</value>
      <webElementGuid>e47a493c-5844-4ab5-881e-4dc1cb87dbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='메일쓰기']/parent::*</value>
      <webElementGuid>58b5e204-edeb-4266-9729-5ea34ae6a9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'main.php?page=write')]</value>
      <webElementGuid>40cf69b2-beba-4c2e-b695-84c6eea29dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>c9f4b1d9-2592-4962-b31d-699862dbd3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'main.php?page=write' and (text() = '메일쓰기' or . = '메일쓰기')]</value>
      <webElementGuid>474f41d6-41c5-4bc3-b84a-5ced4906b584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
