<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mail</name>
   <tag></tag>
   <elementGuidId>6bd09a57-ec28-4113-a684-77e4e4e09ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='mail'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;adminLoginForm&quot;] > fieldset > label > input[name=&quot;mail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tabAdmin >> internal:attr=[placeholder=&quot;아이디&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe32883-58a8-4ddb-83a0-e5968b91d9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4ea513c-7209-4ef0-bc81-e2967c2e98c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>a68c74b2-e6dd-49dc-92f3-a9936fce3b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fText</value>
      <webElementGuid>55927e52-cb2d-42d5-89a0-ac2b80611a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>아이디</value>
      <webElementGuid>71bb7872-ad2c-4663-a205-8d85907eec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabAdmin&quot;)/form[1]/fieldset[1]/label[1]/input[@class=&quot;fText&quot;]</value>
      <webElementGuid>405933b1-8a57-4fb3-a6ea-9e06c8a65511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='mail'])[2]</value>
      <webElementGuid>73398725-27a2-4a47-8606-198186867c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabAdmin']/form/fieldset/label/input</value>
      <webElementGuid>241dd0cb-ce3a-413e-884e-03812e873dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/fieldset/label/input</value>
      <webElementGuid>71cd658f-0572-451b-b4f9-7e5e19d9f234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mail' and @placeholder = '아이디']</value>
      <webElementGuid>4c664999-a145-46f5-ac2d-89f08c942d21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
