<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fChk check-to-me</name>
   <tag></tag>
   <elementGuidId>1adcba2b-dc16-4eee-9150-8c31d613c193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.fChk.check-to-me</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;내게쓰기&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>925a0f9b-3e8c-49ed-b357-d661052d8810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>02057292-4e1c-4559-9b5f-7f6463937617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fChk check-to-me</value>
      <webElementGuid>879383e2-29a5-4f23-b618-e231513ae927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-myname</name>
      <type>Main</type>
      <value>김인환</value>
      <webElementGuid>9498ce8b-9ecb-4756-b29f-33afc876a93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mymail</name>
      <type>Main</type>
      <value>ihkim@knotz.co.kr</value>
      <webElementGuid>a6241799-2b18-4283-afbb-6a393da625ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/form[1]/div[@class=&quot;mBoard typeMail gWrite&quot;]/table[1]/tbody[1]/tr[2]/th[1]/label[@class=&quot;right&quot;]/input[@class=&quot;fChk check-to-me&quot;]</value>
      <webElementGuid>e63b8ff0-c4e9-458a-a118-a6062c0e9c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>51ad6e94-b993-4fff-9ea1-93ab30baf13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/div[2]/table/tbody/tr[2]/th/label/input</value>
      <webElementGuid>c30ecdd7-7ab1-4f4c-9d75-b8cfbc137783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/label/input</value>
      <webElementGuid>ba4808e6-c982-4b59-9043-d699f6222b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>8fa9d5c9-2d91-4f10-a513-f5467820ffe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
