<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__mail</name>
   <tag></tag>
   <elementGuidId>1ed18ed4-7420-4231-b88d-8895f2875306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;메일&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8d25c1f-5a61-42ca-9d9d-a42886e5634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn2 btn-default</value>
      <webElementGuid>fa8648df-0f92-4357-badc-bacecb205905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>d9acb3fa-e901-4b1a-aa4b-0a98ae35c4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:LoginToOWA(2);</value>
      <webElementGuid>9a9ed93d-1c09-4195-bad1-dd4b0195dbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>메일</value>
      <webElementGuid>461b7b32-092f-45b7-b183-f69c7a7ba684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)</value>
      <webElementGuid>eb603482-bdca-4afc-87cc-c57ecae3ddf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mail']</value>
      <webElementGuid>ba9d9b95-a383-42a9-bf4a-10c071f813d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/h2/div/button[2]</value>
      <webElementGuid>8e23439e-8869-487b-9625-e6dba2f4e189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='김인환'])[2]/following::button[2]</value>
      <webElementGuid>0ee69f4f-31b9-4a8d-8fae-6dafab2dae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='출근체크'])[1]/preceding::button[1]</value>
      <webElementGuid>1a455868-c3fb-49f4-bc78-26d52d739a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='퇴근체크'])[1]/preceding::button[2]</value>
      <webElementGuid>59a846e7-82ef-4da8-8339-8e46eda2eaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='메일']/parent::*</value>
      <webElementGuid>9c3fff0b-6bf5-41d9-b2ad-b5131f58fc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/div/button[2]</value>
      <webElementGuid>9709383f-c5f6-4c41-9087-3cff9b63bba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mail' and (text() = '메일' or . = '메일')]</value>
      <webElementGuid>53345c23-12a9-4497-b446-61991445a747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
